# Generated by Django 3.2.14 on 2022-07-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_procedure_updates_and_keyword_lookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
