# Generated by Django 3.2.16 on 2023-01-20 20:24

import django.db.models.deletion
import django.db.models.functions.text
import django_extensions.db.fields
import django_userforeignkey.models.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20230109_1817"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("care", "0003_procedure_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("address_line_1", models.CharField(blank=True, max_length=255, null=True)),
                ("address_line_2", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("name_first", models.CharField(blank=True, max_length=255, null=True)),
                ("name_last", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("name_middle", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_fax", phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, null=True, region=None)),
                ("phone_home", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ("phone_mobile", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ("phone_work", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ("placeholder", models.CharField(blank=True, max_length=255, null=True)),
                ("pms_created_at", models.DateTimeField(null=True)),
                ("zip_code", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization")),
            ],
        ),
        migrations.CreateModel(
            name="PracticePatient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="care.patient")),
                ("practice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.practice")),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="practices",
            field=models.ManyToManyField(related_name="patients", through="care.PracticePatient", to="core.Practice"),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("appointment_end_at", models.DateTimeField(db_index=True)),
                ("appointment_start_at", models.DateTimeField(db_index=True)),
                ("confirmed_at", models.DateTimeField(null=True)),
                ("did_patient_miss", models.BooleanField(null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_new_patient", models.BooleanField(db_index=True, null=True)),
                ("note", models.TextField(null=True)),
                ("pms_created_at", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("DELETED", "Deleted")],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("approximate_total_currency", models.CharField(default="USD", max_length=3)),
                ("approximate_total_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=24)),
                ("procedures", models.JSONField(null=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="care.patient")),
                ("practice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="core.practice")),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="practicepatient",
            constraint=models.UniqueConstraint(fields=("practice_id", "patient_id"), name="unique_practice_with_patient"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(django.db.models.functions.text.Upper("name_last"), name="name_last_case_insensitive"),
        ),
    ]
