# Generated by Django 3.2.10 on 2021-12-15 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('owner', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('source_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('destination_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('error_code', models.IntegerField(null=True)),
                ('to_numbers', models.JSONField()),
                ('from_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('text', models.CharField(max_length=2048)),
                ('message_status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('queued', 'Queued'), ('received', 'Received'), ('sending', 'Sending'), ('sent', 'Sent'), ('undelivered', 'Undelivered')], max_length=255)),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField(null=True)),
                ('direction', models.CharField(max_length=255)),
                ('media', models.JSONField(null=True)),
                ('segment_count', models.IntegerField(null=True)),
                ('priority', models.CharField(choices=[('default', 'Default'), ('high', 'High')], default='default', max_length=255)),
                ('expiration', models.DateTimeField(null=True)),
                ('tag', models.CharField(max_length=180)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smsmessage_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smsmessage_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
