# Generated by Django 3.2.11 on 2022-01-09 02:36

from django.db import migrations, models
import django_extensions.db.fields
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmessage',
            old_name='to_date_time',
            new_name='delivered_date_time',
        ),
        migrations.RenameField(
            model_name='smsmessage',
            old_name='from_date_time',
            new_name='sent_date_time',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='bandwidth_id',
            field=models.CharField(default=shortuuid.uuid, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
