# Generated by Django 3.2.6 on 2021-11-16 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contact"),
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="contact",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.contact"),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
