# Generated by Django 3.2.11 on 2022-01-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_refine_ids_and_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="error_message",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="errored_date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
