# Generated by Django 3.2.10 on 2021-12-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_change_Contact_to_Patient'),
        ('inbox', '0002_move_contact_model_to_core'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='contact',
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient'),
        ),
    ]
