# Generated by Django 3.2.10 on 2021-12-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_move_contact_model_to_core"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smsmessage",
            old_name="to_date_time",
            new_name="delivered_date_time",
        ),
        migrations.RenameField(
            model_name="smsmessage",
            old_name="from_date_time",
            new_name="sent_date_time",
        ),
    ]
