# Generated by Django 3.2.12 on 2022-02-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20220109_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsmessage',
            name='source_number',
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='sent_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
