# Generated by Django 3.2.16 on 2023-01-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0005_alter_smsmessage_message_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="message_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("message-delivered", "Message Delivered"),
                    ("message-failed", "Message Failed"),
                    ("message-received", "Message Received"),
                    ("message-sending", "Message Sending"),
                    ("bandwidth_message_delivered", "Bandwidth Message Delivered"),
                    ("bandwidth_message_failed", "Bandwidth Message Failed"),
                    ("bandwidth_message_received", "Bandwidth Message Received"),
                    ("bandwidth_message_sending", "Bandwidth Message Sending"),
                    ("message_sent_to_bandwidth", "Message Sent To Bandwidth"),
                    ("message_init", "Message Init"),
                ],
                max_length=255,
            ),
        ),
    ]
