# Generated by Django 3.2.16 on 2023-01-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0004_auto_20230120_2024"),
        ("inbox", "0006_alter_smsmessage_message_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="patient",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="care.patient"),
        ),
    ]
