images: $_DJANGO_DOCKER_REPO
steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: [ 'build', '-t', '${_DJANGO_DOCKER_REPO}', '.']
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_DJANGO_DOCKER_REPO}"]
  - id: "deploy container image to GKE"
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=${_KUBERNETES_RESOURCE_FILE}
    - --location=us-west4
    - --cluster=peerlogic-api
  - id: "apply migrations"
    name: "${_DJANGO_DOCKER_REPO}"
    args:
      [
        "python",
        "manage.py",
        "migrate",
      ]
    env:
    - 'DJANGO_SECRET_KEY=$_DJANGO_SECRET_KEY'
    - 'POSTGRES_USER=$_POSTGRES_USER'
    - 'POSTGRES_DB=$_POSTGRES_DB'
    - 'POSTGRES_PASSWORD=$_POSTGRES_PASSWORD'
  - id: "Collect static"
    name: "${_DJANGO_DOCKER_REPO}"
    args:
      [
        "python",
        "manage.py",
        "collectstatic",
      ]  
    env:
    - 'DJANGO_SECRET_KEY=$_DJANGO_SECRET_KEY'
    - 'POSTGRES_USER=$_POSTGRES_USER'
    - 'POSTGRES_DB=$_POSTGRES_DB'
    - 'POSTGRES_PASSWORD=$_POSTGRES_PASSWORD'
  - id: "Rsync Static files to bucket"
    name:  'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gsutil -m rsync -r '/workspace/static' 'gs://${PROJECT_ID}/static'

substitutions:
  _DJANGO_DOCKER_REPO: gcr.io/peerlogic-api-prod/peerlogic-api
  _REGION: us-west4

