steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: [ 'build', '-t', '${_DOCKER_REPO}', '.']
    timeout: 500s
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_DOCKER_REPO}"]
  - id: "Delete past jobs"
    name: "gcr.io/cloud-builders/kubectl"
    args: ["delete", "jobs", "--all"]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-west4-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=peerlogic-api'
  # TODO: figure out how to set celery and migration images as well
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['set', 'image', 'deployment/peerlogic-api', 'peerlogic-api=${_DOCKER_REPO}']
  #   env:
  #   - 'CLOUDSDK_COMPUTE_ZONE=us-west4-a'
  #   - 'CLOUDSDK_CONTAINER_CLUSTER=peerlogic-api'
  - id: "deploy container image to GKE"
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=${_KUBERNETES_RESOURCE_FILE}
    - --location=us-west4-a
    - --cluster=peerlogic-api
  - id: "Collect static"
    name: "${_DOCKER_REPO}"
    args:
      [
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--noinput"
      ]  
    env:
    - 'DJANGO_SECRET_KEY=$_DJANGO_SECRET_KEY'
    - 'POSTGRES_USER=$_POSTGRES_USER'
    - 'POSTGRES_DB=$_POSTGRES_DB'
    - 'POSTGRES_PASSWORD=$_POSTGRES_PASSWORD'
  - id: "Rsync Static files to bucket"
    name:  'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gsutil -m rsync -r '/workspace/static' 'gs://${PROJECT_ID}/static'

substitutions:
  _REGION: us-west4

