version: '3.8'

services:

  postgres:
      image: postgres:10-alpine
      ports:
          - "5432:5432"
      env_file:
          - .env
      volumes:
          - ./volumes/postgres:/var/lib/postgresql

  web:
      image: gcr.io/peerlogic-api/peerlogic-api
      volumes:
          - .:/app
      ports:
          - 8000:8000
      depends_on:
          - postgres
      env_file:
          - .env
      environment:
          - PORT=8000
          - WAIT_HOSTS=postgres:5432
          - WAIT_HOSTS_TIMEOUT=300
          - WAIT_SLEEP_INTERVAL=30
          - WAIT_HOST_CONNECT_TIMEOUT=30
          - DB_HOST=postgres

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
