version: '3.8'

services:

  postgres:
      image: postgres:10-alpine
      ports:
          - "5432:5432"
      env_file:
          - .env
      volumes:
          - ./volumes/postgres:/var/lib/postgresql

  api:
      build: .
      volumes:
          - .:/app
      ports:
          - 8000:8000
      depends_on:
          - postgres
      env_file:
          - .env
      environment:
          - PORT=8000
          - WAIT_HOSTS=postgres:5432
          - WAIT_HOSTS_TIMEOUT=300
          - WAIT_SLEEP_INTERVAL=30
          - WAIT_HOST_CONNECT_TIMEOUT=30
          - DB_HOST=postgres

  worker:
      build: .
      command: ["celery", "-A", "peerlogic", "worker", "-l", "INFO"]
      volumes:
          - .:/app
      depends_on:
          - postgres
      env_file:
          - .env
      environment:
          - PORT=8000
          - WAIT_HOSTS=postgres:5432
          - WAIT_HOSTS_TIMEOUT=300
          - WAIT_SLEEP_INTERVAL=60
          - WAIT_HOST_CONNECT_TIMEOUT=60
          - DB_HOST=postgres
          - CELERY_BROKER_URL=redis://redis:6379/0
          - CELERY_RESULT_BACKEND=redis://redis:6379/0

  beat:
      build: .
      command: ["celery", "-A", "peerlogic", "beat", "-l", "INFO", "-S", "django_celery_beat.schedulers:DatabaseScheduler"]
      volumes:
          - .:/app
      depends_on:
          - postgres
      env_file:
          - .env
      environment:
          - PORT=8000
          - WAIT_HOSTS=postgres:5432,redis:6379
          - WAIT_HOSTS_TIMEOUT=300
          - WAIT_SLEEP_INTERVAL=180
          - WAIT_HOST_CONNECT_TIMEOUT=180
          - DB_HOST=postgres
          - CELERY_BROKER_URL=redis://redis:6379/0
          - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
