version: '3.8'

services:

  postgres:
      image: postgres:10-alpine
      environment:
        - POSTGRES_DB=peerlogic
        - POSTGRES_PASSWORD=password
      ports:
          - "5432:5432"
      env_file:
          - .env
      volumes:
          - ./volumes/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
          - .:/peerlogic
      ports:
          - "8000:8000"
      depends_on:
          - postgres
      env_file:
          - .env

  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
