# Generated by Django 3.2.10 on 2021-12-14 01:37

import core.managers
import core.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_userforeignkey.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=300, verbose_name="name")),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.Permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", core.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300, unique=True, verbose_name="name")),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="name")),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("dentistry_general", "Dentistry General"),
                            ("dentistry_pediatric", "Dentistry Pediatric"),
                            ("dentistry_orthodontic", "Dentistry Orthodontic"),
                            ("dentistry_cosmetic", "Dentistry Cosmetic"),
                            ("dentistry_periodontic", "Dentistry Periodontic"),
                            ("dentistry_prosthodontic", "Dentistry Prosthodontic"),
                            ("dentistry_endodontic", "Dentistry Endodontic"),
                            ("dentistry_oral_surgery", "Dentistry Oral Surgery"),
                            ("dentistry_others", "Dentistry Others"),
                            ("others", "Others"),
                        ],
                        default="dentistry_general",
                        max_length=250,
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practice_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practice_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
            ],
            options={
                "verbose_name": "practice",
                "verbose_name_plural": "practices",
            },
            managers=[
                ("objects", core.managers.PracticeManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserTelecom",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("phone_sms", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ("phone_callback", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usertelecom_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usertelecom_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPerson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userperson_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userperson_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.person")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PracticeTelecom",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("domain", models.CharField(db_index=True, max_length=80)),
                ("phone_sms", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ("phone_callback", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practicetelecom_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practicetelecom_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                ("practice", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.practice")),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PracticePerson",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practiceperson_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practiceperson_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                ("person", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.person")),
                ("practice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.practice")),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="practice",
            name="persons",
            field=models.ManyToManyField(through="core.PracticePerson", to="core.Person"),
        ),
        migrations.AddField(
            model_name="person",
            name="user_accounts",
            field=models.ManyToManyField(through="core.UserPerson", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("name_first", models.CharField(blank=True, db_index=True, max_length=255)),
                ("name_last", models.CharField(blank=True, db_index=True, max_length=255)),
                ("placeholder", models.CharField(blank=True, max_length=255)),
                ("phone_mobile", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default="", max_length=128, region=None)),
                ("phone_home", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default="", max_length=128, region=None)),
                ("phone_work", phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default="", max_length=128, region=None)),
                ("phone_fax", phonenumber_field.modelfields.PhoneNumberField(blank=True, default="", max_length=128, region=None)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("zip_code", models.CharField(max_length=50)),
                ("zip_code_add_on", models.CharField(blank=True, max_length=50)),
                ("date_of_birth", models.DateTimeField()),
                ("velox_extract_data", models.JSONField(default=core.models.Patient.velox_extract_data_default)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("client_type", models.CharField(choices=[("pms", "Practice Management Software")], default="pms", max_length=50)),
                ("rest_base_url", models.CharField(max_length=300)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                ("practice", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="core.practice")),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
    ]
