# Generated by Django 3.2.10 on 2021-12-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="velox_extract_data",
        ),
    ]
