# Generated by Django 3.2.6 on 2021-08-06 23:58

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201211_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
