# Generated by Django 3.2.11 on 2022-02-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_voip_provider_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
