# Generated by Django 3.2.12 on 2022-03-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_practice_have_active_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetelecom',
            name='practice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_telecom', to='core.practice'),
        ),
    ]
