# Generated by Django 3.2.9 on 2021-11-17 01:25

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_contact"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="expires_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="refresh_token",
        ),
    ]
