# Generated by Django 3.2.12 on 2022-05-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_practicetelecom_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expiry',
        ),
    ]
