# Generated by Django 3.2.13 on 2022-05-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_practicetelecom_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voipprovider',
            name='integration_type',
            field=models.CharField(choices=[('netsapiens', 'Netsapiens'), ('jive', 'Jive')], default='netsapiens', max_length=150),
        ),
    ]
