# Generated by Django 3.2.13 on 2022-06-17 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_voipprovider_integration_type'),
        ('core', '0009_user_auth0_id'),
    ]

    operations = [
    ]
