# Generated by Django 3.2.10 on 2021-12-09 16:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_and_telecom_caller_name_info_indices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile_number',
            new_name='phone_mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fax_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_home',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default=None, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_work',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default=None, max_length=128, region=None),
        ),
    ]
