# Generated by Django 3.2.10 on 2021-12-08 23:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact_and_telecom_caller_name_info_indices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile_number',
            new_name='phone_mobile',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_home',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_work',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default=None, max_length=128, null=True, region=None),
        ),
    ]
