# Generated by Django 3.2.10 on 2021-12-10 21:40

import core.models
from django.db import migrations, models
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_phone_names_and_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, db_index=True, max_length=255)),
                ('name_last', models.CharField(blank=True, db_index=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('phone_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('phone_home', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('phone_work', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('phone_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(max_length=50)),
                ('zip_code_add_on', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('velox_extract_data', models.JSONField(default=core.models.Patient.velox_extract_data_default)),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='modified_by',
        ),
    ]
