# Generated by Django 3.2.15 on 2022-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_create_insurance_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insuranceprovider",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
