# Generated by Django 3.2.15 on 2022-09-12 18:25

import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_practices_have_us_state_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingCampaignPhoneNumber",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketingcampaignphonenumber_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marketingcampaignphonenumber_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_telephone_numbers",
                        to="core.practice",
                        verbose_name="The practice that owns the marketing number",
                    ),
                ),
            ],
            options={
                "unique_together": {("practice_id", "phone_number")},
            },
        ),
    ]
