# Generated by Django 3.2.15 on 2022-09-13 22:50

import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_marketingcampaignphonenumber"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PracticeGroup",
            new_name="Organization",
        ),
        migrations.RenameField(
            model_name="Practice",
            old_name="practice_group",
            new_name="organization",
        ),
    ]
