# Generated by Django 3.2.16 on 2022-11-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_practice_include_in_benchmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='industry',
            field=models.CharField(blank=True, choices=[('dentistry_general', 'Dentistry General'), ('dentistry_pediatric', 'Dentistry Pediatric'), ('dentistry_orthodontic', 'Dentistry Orthodontic'), ('dentistry_cosmetic', 'Dentistry Cosmetic'), ('dentistry_periodontic', 'Dentistry Periodontic'), ('dentistry_prosthodontic', 'Dentistry Prosthodontic'), ('dentistry_endodontic', 'Dentistry Endodontic'), ('dentistry_oral_surgery', 'Dentistry Oral Surgery'), ('dentistry_others', 'Dentistry Others'), ('others', 'Others')], max_length=250),
        ),
        migrations.AlterField(
            model_name='voipprovider',
            name='integration_type',
            field=models.CharField(choices=[('netsapiens', 'Netsapiens'), ('jive', 'GoTo / Jive')], default='netsapiens', max_length=150),
        ),
    ]
