# Generated by Django 3.2.16 on 2023-01-04 15:13

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20221114_2028"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="practice",
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="name_middle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="organization",
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, to="core.organization"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default="", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name_first",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name_last",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="PracticePatient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.patient")),
                ("practice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.practice")),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("appointment_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("DELETED", "Deleted")],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("deleted_at", models.DateTimeField(db_index=True, null=True)),
                ("approximate_total_currency", models.CharField(default="USD", max_length=3)),
                ("approximate_total_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=24)),
                ("procedures", models.JSONField(null=True)),
                ("patient_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="core.patient")),
                ("practice_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="core.practice")),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="practices",
            field=models.ManyToManyField(related_name="patients", through="core.PracticePatient", to="core.Practice"),
        ),
        migrations.AddConstraint(
            model_name="practicepatient",
            constraint=models.UniqueConstraint(fields=("practice_id", "patient_id"), name="unique_practice_with_patient"),
        ),
    ]
