# Generated by Django 3.2.16 on 2023-01-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20230104_2213"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="patient_id",
            new_name="patient",
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="practice_id",
            new_name="practice",
        ),
    ]
