# Generated by Django 3.2.16 on 2023-01-09 18:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_auto_20230105_2154"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={},
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(django.db.models.functions.text.Upper("name_last"), name="name_last_case_insensitive"),
        ),
    ]
