# Generated by Django 3.2.16 on 2023-01-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0007_alter_smsmessage_patient"),
        ("nexhealth_integration", "0003_auto_20230120_2024"),
        ("core", "0024_auto_20230109_1817"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="practices",
        ),
        migrations.RemoveField(
            model_name="practicepatient",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="practicepatient",
            name="practice",
        ),
        migrations.RemoveField(
            model_name="userpatient",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userpatient",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="userpatient",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="userpatient",
            name="user",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="PracticePatient",
        ),
        migrations.DeleteModel(
            name="UserPatient",
        ),
    ]
