# Generated by Django 3.2.6 on 2021-11-16 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLabel',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('metric', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calllabel_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calllabel_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('telecom_call_id', models.CharField(max_length=255)),
                ('caller_audio_url', models.CharField(max_length=255)),
                ('callee_audio_url', models.CharField(max_length=255)),
                ('call_start', models.DateTimeField()),
                ('call_end', models.DateTimeField()),
                ('duration_seconds', models.DurationField()),
                ('connect_duration_seconds', models.DurationField()),
                ('progress_time_seconds', models.DurationField()),
                ('call_direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], max_length=50)),
                ('sip_caller_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sip_caller_name', models.CharField(blank=True, max_length=255)),
                ('sip_callee_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sip_callee_name', models.CharField(blank=True, max_length=255)),
                ('checked_voicemail', models.BooleanField()),
                ('went_to_voicemail', models.BooleanField()),
                ('call_connection', models.CharField(choices=[('missed', 'Missed'), ('connected', 'Connected')], max_length=50)),
                ('who_terminated_call', models.CharField(choices=[('caller', 'Caller'), ('callee', 'Callee')], max_length=50)),
                ('referral_source', models.CharField(choices=[('patient_referral', 'Patient Referral'), ('medical_provider', 'Medical Provider'), ('dental_provider', 'Dental Provider'), ('web_search', 'Web Search'), ('social_media', 'Social Media'), ('insurance', 'Insurance'), ('paid_advertising', 'Paid Advertising'), ('unknown', 'Unknown'), ('other', 'Other')], max_length=50)),
                ('caller_type', models.CharField(choices=[('new_patient', 'New Patient'), ('existing_patient', 'Existing Patient'), ('contractor_vendor', 'Contractor Vendor'), ('agent', 'Agent')], max_length=50)),
                ('callee_type', models.CharField(choices=[('new_patient', 'New Patient'), ('existing_patient', 'Existing Patient'), ('contractor_vendor', 'Contractor Vendor'), ('agent', 'Agent')], max_length=50)),
                ('metadata_file_uri', models.CharField(max_length=255)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='auth.group', verbose_name='The domain the call pertains to')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
