# Generated by Django 3.2.10 on 2021-12-14 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("telecom_call_id", models.CharField(max_length=255)),
                ("caller_audio_url", models.CharField(max_length=255)),
                ("callee_audio_url", models.CharField(max_length=255)),
                ("call_start_time", models.DateTimeField()),
                ("call_end_time", models.DateTimeField()),
                ("duration_seconds", models.DurationField()),
                ("connect_duration_seconds", models.DurationField()),
                ("progress_time_seconds", models.DurationField()),
                (
                    "call_direction",
                    models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound"), ("internal", "Internal")], db_index=True, max_length=50),
                ),
                ("sip_caller_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("sip_caller_name", models.CharField(blank=True, max_length=255)),
                ("sip_callee_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("sip_callee_name", models.CharField(blank=True, max_length=255)),
                ("checked_voicemail", models.BooleanField()),
                ("went_to_voicemail", models.BooleanField()),
                ("call_connection", models.CharField(choices=[("missed", "Missed"), ("connected", "Connected")], max_length=50)),
                ("who_terminated_call", models.CharField(choices=[("caller", "Caller"), ("callee", "Callee")], max_length=50)),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("patient_referral", "Patient Referral"),
                            ("medical_provider", "Medical Provider"),
                            ("dental_provider", "Dental Provider"),
                            ("web_search", "Web Search"),
                            ("social_media", "Social Media"),
                            ("insurance", "Insurance"),
                            ("paid_advertising", "Paid Advertising"),
                            ("not_applicable", "Not Applicable"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("caller_type", models.CharField(choices=[("agent", "Agent"), ("non_agent", "Non Agent")], max_length=50)),
                ("callee_type", models.CharField(choices=[("agent", "Agent"), ("non_agent", "Non Agent")], max_length=50)),
                ("metadata_file_uri", models.CharField(max_length=255)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "practice_telecom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="core.practicetelecom",
                        verbose_name="The practice telecom id the call pertains to",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelecomCallerNameInfo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, primary_key=True, region=None, serialize=False)),
                ("caller_name", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                (
                    "caller_name_type",
                    models.CharField(choices=[("business", "Business"), ("consumer", "Consumer"), ("undetermined", "Undetermined")], max_length=50, null=True),
                ),
                ("source", models.CharField(choices=[("peerlogic", "Peerlogic"), ("twilio", "Twilio")], default=None, max_length=50, null=True)),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telecomcallernameinfo_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telecomcallernameinfo_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallLabel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ("metric", models.CharField(db_index=True, max_length=255)),
                ("label", models.CharField(db_index=True, max_length=255)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="labeled_calls", to="calls.call", verbose_name="The call being labeled"
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calllabel_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calllabel_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentEngagedWith",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                (
                    "non_agent_engagement_persona_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_patient", "New Patient"),
                            ("existing_patient", "Existing Patient"),
                            ("contractor_vendor", "Contractor Vendor"),
                            ("insurance_provider", "Insurance Provider"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="engaged_in_calls", to="calls.call", verbose_name="The call engaged with"
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agentengagedwith_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
                (
                    "modified_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agentengagedwith_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that is automatically assigned",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified_at",
                "abstract": False,
            },
        ),
    ]
