# Generated by Django 3.2.11 on 2022-01-25 20:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_telecom_caller_name_info_adds_carrier_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='callee_audio_url',
        ),
        migrations.RemoveField(
            model_name='call',
            name='caller_audio_url',
        ),
        migrations.RemoveField(
            model_name='call',
            name='telecom_call_id',
        ),
        migrations.AlterField(
            model_name='call',
            name='call_connection',
            field=models.CharField(blank=True, choices=[('missed', 'Missed'), ('connected', 'Connected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='callee_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('non_agent', 'Non Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='caller_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('non_agent', 'Non Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='checked_voicemail',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='connect_duration_seconds',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='metadata_file_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='call',
            name='progress_time_seconds',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='sip_callee_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='call',
            name='sip_caller_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='call',
            name='went_to_voicemail',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='who_terminated_call',
            field=models.CharField(blank=True, choices=[('caller', 'Caller'), ('callee', 'Callee')], max_length=50),
        ),
    ]
