# Generated by Django 3.2.9 on 2021-12-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_TelecomCallerNameInfoAdditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcallernameinfo',
            name='source',
            field=models.CharField(choices=[('peerlogic', 'Peerlogic'), ('twilio', 'Twilio')], default='peerlogic', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telecomcallernameinfo',
            name='caller_name_type',
            field=models.CharField(choices=[('business', 'Business'), ('consumer', 'Consumer'), ('undetermined', 'Undetermined')], max_length=50),
        ),
    ]
