# Generated by Django 3.2.9 on 2021-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_telecom_caller_name_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telecomcallernameinfo",
            name="caller_name",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
