# Generated by Django 3.2.9 on 2021-12-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_telecom_caller_name_info_source_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcallernameinfo',
            name='caller_name_type',
            field=models.CharField(choices=[('business', 'Business'), ('consumer', 'Consumer'), ('undetermined', 'Undetermined')], max_length=50, null=True),
        ),
    ]
