# Generated by Django 3.2.9 on 2021-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_contact_and_telecom_caller_name_info_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcallernameinfo',
            name='caller_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
