# Generated by Django 3.2.10 on 2021-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_follow_django_standards_with_telecom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecomcallernameinfo',
            name='caller_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
