# Generated by Django 3.2.11 on 2022-01-25 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0004_callaudiopartial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallAudioPartial',
        )
    ]
