# Generated by Django 3.2.11 on 2022-01-28 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0005_delete_callaudiopartial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAudioPartial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mime_type', models.CharField(choices=[('audio/PCMU', 'Audio Pcmu'), ('audio/GSM', 'Audio Gsm'), ('audio/WAV', 'Audio Wav')], max_length=180)),
                ('status', models.CharField(choices=[], default='retrieval_from_provider_in_progress', max_length=80)),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallPartial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callpartial_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callpartial_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallTranscriptPartial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mime_type', models.CharField(choices=[('text/plain', 'Text Plain')], default='text/plain', max_length=180)),
                ('status', models.CharField(choices=[], default='retrieval_from_provider_in_progress', max_length=80)),
                ('call_audio_partial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.callaudiopartial')),
                ('call_partial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.callpartial')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscriptionpartial_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscriptionpartial_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='callaudiopartial',
            name='call_partial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.callpartial'),
        ),
        migrations.AddField(
            model_name='callaudiopartial',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callaudiopartial_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
        migrations.AddField(
            model_name='callaudiopartial',
            name='modified_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callaudiopartial_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
    ]
