# Generated by Django 3.2.12 on 2022-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_create_call_partials_and_transcripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltranscriptpartial',
            name='mime_type',
            field=models.CharField(choices=[('text/plain', 'Text Plain'), ('application/json', 'Application Json')], default='text/plain', max_length=180),
        ),
    ]
