# Generated by Django 3.2.11 on 2022-02-03 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0007_add_mimetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltranscriptpartial',
            name='speech_to_text_model_type',
            field=models.CharField(choices=[('google', 'Google'), ('facebook_ai', 'Facebook Ai')], default='google', max_length=80),
        ),
        migrations.AddField(
            model_name='calltranscriptpartial',
            name='transcript_type',
            field=models.CharField(choices=[('full_text', 'Full Text'), ('channel_1_text', 'Channel 1 Text'), ('channel_2_text', 'Channel 2 Text')], default='full_text', max_length=80),
        ),
        migrations.AlterField(
            model_name='calltranscriptpartial',
            name='mime_type',
            field=models.CharField(choices=[('text/plain', 'Text Plain'), ('application/json', 'Application Json')], default='text/plain', max_length=180),
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('mime_type', models.CharField(choices=[('text/plain', 'Text Plain'), ('application/json', 'Application Json')], default='text/plain', max_length=180)),
                ('transcript_type', models.CharField(choices=[('full_text', 'Full Text'), ('channel_1_text', 'Channel 1 Text'), ('channel_2_text', 'Channel 2 Text')], default='full_text', max_length=80)),
                ('speech_to_text_model_type', models.CharField(choices=[('google', 'Google'), ('facebook_ai', 'Facebook Ai')], default='google', max_length=80)),
                ('status', models.CharField(choices=[], default='retrieval_from_provider_in_progress', max_length=80)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscript_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscript_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
