# Generated by Django 3.2.12 on 2022-02-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_practice_have_active_flag'),
        ('calls', '0008_call_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.practice', verbose_name='The practice that made or received the call'),
        ),
    ]
