# Generated by Django 3.2.12 on 2022-02-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    def update_practice_with_practice_telecom(apps, schema_editor):
        # We can't import the Call model directly as it may be a newer
        Call = apps.get_model("calls", "Call")
        Practice = apps.get_model("core", "Practice")
        peerlogic_practice = Practice.objects.get_or_create(name="Peerlogic")
        for c in Call.objects.all():
            practice_telecom = c.practice_telecom
            if practice_telecom is not None:
                c.practice = practice_telecom.practice
            else:
                c.practice = peerlogic_practice
            c.save()

    dependencies = [
        ("calls", "0009_calls_associated_with_mandatory_practice_step_1_add_column"),
    ]

    operations = [
        migrations.RunPython(update_practice_with_practice_telecom)
    ]
