# Generated by Django 3.2.12 on 2022-02-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_practice_have_active_flag'),
        ('calls', '0010_calls_associated_with_mandatory_practice_step_2_populate_colum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='practice_telecom',
        ),
        migrations.AlterField(
            model_name='call',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='core.practice', verbose_name='The practice that made or received the call'),
        ),
    ]
