# Generated by Django 3.2.11 on 2022-02-04 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_calls_associated_with_mandatory_practice_step_3_murder_the_old_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpartial',
            name='time_interaction_ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callpartial',
            name='time_interaction_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
