# Generated by Django 3.2.11 on 2022-02-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0012_call_partial_interaction_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltranscript',
            name='publish_event_on_patch',
            field=models.BooleanField(default=False),
        ),
    ]
