# Generated by Django 3.2.11 on 2022-02-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_callaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='callaudio',
            name='call',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calls.call'),
            preserve_default=False,
        ),
    ]
