# Generated by Django 3.2.12 on 2022-02-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0015_callaudio_call'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callpartial',
            options={},
        ),
        migrations.AddConstraint(
            model_name='callpartial',
            constraint=models.UniqueConstraint(fields=('call', 'time_interaction_started', 'time_interaction_ended'), name='unique time constraints for every call'),
        ),
    ]
