# Generated by Django 3.2.12 on 2022-02-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0016_call_partial_unique_time_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='metadata_file_uri',
        ),
    ]
