# Generated by Django 3.2.12 on 2022-03-31 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0017_remove_call_metadata_file_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOutcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('call_outcome_type', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, max_length=50)),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='callaudiopartial',
            name='call_partial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_audio_partials', to='calls.callpartial'),
        ),
        migrations.CreateModel(
            name='CallPurpose',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('call_purpose_type', models.CharField(blank=True, choices=[('new_appointment', 'New Appointment'), ('reschedule', 'Reschedule'), ('confirm_appointment', 'Confirm Appointment'), ('pricing', 'Pricing'), ('billing', 'Billing')], db_index=True, max_length=50)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_purposes', to='calls.call', verbose_name='Purpose of the call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callpurpose_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callpurpose_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallOutcomeReason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('call_outcome_reason_type', models.CharField(blank=True, choices=[('not_enough_information_possesed_by_patient_or_agent', 'Not Enough Information Possesed By Patient Or Agent'), ('procedure_not_offered', 'Procedure Not Offered'), ('caller_indifference', 'Caller Indifference'), ('insurance', 'Insurance'), ('pricing', 'Pricing'), ('lost', 'Lost'), ('treatment_not_offered', 'Treatment Not Offered'), ('scheduling', 'Scheduling'), ('day_or_time_not_available', 'Day Or Time Not Available'), ('too_expensive', 'Too Expensive'), ('call_interrupted', 'Call Interrupted'), ('insurance_not_taken', 'Insurance Not Taken')], db_index=True, max_length=75)),
                ('call_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_reason_results', to='calls.calloutcome', verbose_name='The source outcome')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calloutcomereason_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calloutcomereason_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='calloutcome',
            name='call_purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_results', to='calls.callpurpose', verbose_name='The source purpose for this outcome'),
        ),
        migrations.AddField(
            model_name='calloutcome',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calloutcome_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
        migrations.AddField(
            model_name='calloutcome',
            name='modified_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calloutcome_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
    ]
