# Generated by Django 3.2.12 on 2022-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0018_auto_20220331_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='calloutcome',
            name='raw_call_outcome_model_run_id',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calloutcomereason',
            name='raw_call_outcome_reason_model_run_id',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callpurpose',
            name='raw_call_purpose_model_run_id',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
    ]
