# Generated by Django 3.2.12 on 2022-04-02 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0019_auto_20220331_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTranscriptFragment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('text', models.TextField()),
                ('telecom_persona_type', models.CharField(choices=[('caller', 'Caller'), ('callee', 'Callee')], max_length=50)),
                ('raw_call_transcript_fragment_model_run_id', models.CharField(max_length=22)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_fragments', to='calls.call', verbose_name='a piece of a conversation from a call transcript')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscriptfragment_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscriptfragment_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='calltranscript',
            name='raw_call_transcript_model_run_id',
            field=models.CharField(default='', max_length=22),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CallTranscriptFragmentSentiment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('sentiment_score', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=50)),
                ('raw_call_transcript_fragment_sentiment_model_run_id', models.CharField(max_length=22)),
                ('call_transcript_fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_fragment_sentiments', to='calls.calltranscriptfragment', verbose_name='sentiment on a piece of a conversation from a call transcript')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscriptfragmentsentiment_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calltranscriptfragmentsentiment_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
