# Generated by Django 3.2.12 on 2022-04-02 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0021_callsentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLongestPause',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('raw_call_pause_model_run_id', models.CharField(max_length=22)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_pauses', to='calls.call', verbose_name='a pause in conversation detected in the audio or transcript')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calllongestpause_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calllongestpause_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
