# Generated by Django 3.2.12 on 2022-04-04 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0022_calllongestpause'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallProcedureDiscussed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures_discussed', to='calls.call', verbose_name='procedure reference discussed during a call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callprocedurediscussed_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callprocedurediscussed_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_in_which_discussed', to='care.procedure', verbose_name='procedure')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
