# Generated by Django 3.2.12 on 2022-04-06 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0002_procedure_updates_and_keyword_lookup'),
        ('calls', '0023_callprocedurediscussed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callprocedurediscussed',
            name='procedure',
        ),
        migrations.AddField(
            model_name='callprocedurediscussed',
            name='keyword',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ProcedureKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedurekeyword_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedurekeyword_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='care.procedure', verbose_name='procedures associated with a keyword')),
            ],
        ),
        migrations.AddConstraint(
            model_name='procedurekeyword',
            constraint=models.UniqueConstraint(fields=('procedure', 'keyword'), name='unique keyword mapping'),
        ),
    ]
