# Generated by Django 3.2.12 on 2022-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0025_results_history_run_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutcomereason',
            name='call_outcome_reason_type',
            field=models.CharField(blank=True, choices=[('not_enough_information_possesed_by_patient_or_agent', 'Not Enough Information Possesed By Patient Or Agent'), ('procedure_not_offered', 'Procedure Not Offered'), ('caller_indifference', 'Caller Indifference'), ('insurance', 'Insurance'), ('pricing', 'Pricing'), ('lost', 'Lost'), ('treatment_not_offered', 'Treatment Not Offered'), ('scheduling', 'Scheduling'), ('day_or_time_not_available', 'Day Or Time Not Available'), ('too_expensive', 'Too Expensive'), ('call_interrupted', 'Call Interrupted'), ('insurance_not_taken', 'Insurance Not Taken'), ('others', 'Others')], db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='callpurpose',
            name='call_purpose_type',
            field=models.CharField(blank=True, choices=[('new_appointment', 'New Appointment'), ('reschedule', 'Reschedule'), ('confirm_appointment', 'Confirm Appointment'), ('pricing', 'Pricing'), ('billing', 'Billing'), ('others', 'Others')], db_index=True, max_length=50),
        ),
    ]
