# Generated by Django 3.2.12 on 2022-04-08 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0025_results_history_run_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutcomereason',
            name='call_outcome_reason_type',
            field=models.CharField(blank=True, choices=[('not_enough_information_possesed_by_patient_or_agent', 'Not Enough Information Possesed By Patient Or Agent'), ('procedure_not_offered', 'Procedure Not Offered'), ('caller_indifference', 'Caller Indifference'), ('insurance', 'Insurance'), ('pricing', 'Pricing'), ('lost', 'Lost'), ('treatment_not_offered', 'Treatment Not Offered'), ('scheduling', 'Scheduling'), ('day_or_time_not_available', 'Day Or Time Not Available'), ('too_expensive', 'Too Expensive'), ('call_interrupted', 'Call Interrupted'), ('insurance_not_taken', 'Insurance Not Taken'), ('others', 'Others')], db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='callprocedurediscussed',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_procedures', to='calls.call', verbose_name='procedure discussed during a call'),
        ),
        migrations.AlterField(
            model_name='callpurpose',
            name='call_purpose_type',
            field=models.CharField(blank=True, choices=[('new_appointment', 'New Appointment'), ('reschedule', 'Reschedule'), ('confirm_appointment', 'Confirm Appointment'), ('pricing', 'Pricing'), ('billing', 'Billing'), ('others', 'Others')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CallSymptomDiscussed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=50)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_symptoms', to='calls.call', verbose_name='symptom discussed during a call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callsymptomdiscussed_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callsymptomdiscussed_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallProductDiscussed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=50)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_products', to='calls.call', verbose_name='product discussed during a call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callproductdiscussed_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callproductdiscussed_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallInsuranceDiscussed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=50)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_insurances', to='calls.call', verbose_name='insurance discussed during a call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callinsurancediscussed_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callinsurancediscussed_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallCompanyDiscussed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=50)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_companies', to='calls.call', verbose_name='company discussed during a call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callcompanydiscussed_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callcompanydiscussed_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
