# Generated by Django 3.2.12 on 2022-04-21 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0027_discussed_table_creation_and_renames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltranscript',
            name='raw_call_transcript_model_run_id',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
