# Generated by Django 3.2.13 on 2022-05-24 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0028_blankable_raw_call_transcript_model_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldiscussedprocedure',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussed_procedures', to='calls.call', verbose_name='procedure discussed during a call'),
        ),
        migrations.AlterField(
            model_name='calldiscussedprocedure',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calldiscussedprocedure_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
        migrations.AlterField(
            model_name='calldiscussedprocedure',
            name='modified_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calldiscussedprocedure_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned'),
        ),
    ]
