# Generated by Django 3.2.14 on 2022-07-19 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0029_auto_20220524_0441'),
    ]

    operations = [
        migrations.RenameModel('CallDiscussedCompany', 'CallMentionedCompany'),
        migrations.RenameModel('CallDiscussedInsurance', 'CallMentionedInsurance'),
        migrations.RenameModel('CallDiscussedProcedure', 'CallMentionedProcedure'),
        migrations.RenameModel('CallDiscussedProduct', 'CallMentionedProduct'),
        migrations.RenameModel('CallDiscussedSymptom', 'CallMentionedSymptom'),
    ]
