# Generated by Django 3.2.14 on 2022-07-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_mlmodel_vertex_deployed_model_id'),
        ('calls', '0029_auto_20220524_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentengagedwith',
            name='non_agent_engagement_persona_model_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_non_agent_engagement_personas', to='ml.mlmodelresulthistory', verbose_name='ml model run for this non agent engagement persona'),
        ),
        migrations.AddField(
            model_name='agentengagedwith',
            name='raw_non_agent_engagement_persona_model_run_id',
            field=models.CharField(default='                      ', max_length=22),
            preserve_default=False,
        ),
    ]
