# Generated by Django 3.2.14 on 2022-07-25 04:26

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0030_auto_20220719_0123'),
    ]

    operations = [
        migrations.RenameModel('CallDiscussedCompany', 'CallMentionedCompany'),
        migrations.RenameModel('CallDiscussedInsurance', 'CallMentionedInsurance'),
        migrations.RenameModel('CallDiscussedProcedure', 'CallMentionedProcedure'),
        migrations.RenameModel('CallDiscussedProduct', 'CallMentionedProduct'),
        migrations.RenameModel('CallDiscussedSymptom', 'CallMentionedSymptom'),
        migrations.AlterField(
            model_name='callsentiment',
            name='callee_sentiment_score',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('not_applicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='caller_sentiment_score',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('not_applicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='callsentiment',
            name='overall_sentiment_score',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('not_applicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calltranscriptfragmentsentiment',
            name='sentiment_score',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('not_applicable', 'Not Applicable')], max_length=50),
        ),
    ]
