# Generated by Django 3.2.14 on 2022-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0033_agentcallscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcallscore',
            name='metric',
            field=models.CharField(choices=[('scheduling_accommodations', 'Scheduling Accommodations'), ('referral_source', 'Referral Source'), ('procedure_explanation', 'Procedure Explanation'), ('payment_method', 'Payment Method'), ('patient_demographics', 'Patient Demographics'), ('greeting', 'Greeting'), ('agent_overtalk', 'Agent Overtalk')], max_length=180),
        ),
        migrations.AlterField(
            model_name='calloutcome',
            name='call_outcome_type',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('not_applicable', 'Not Applicable')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='calloutcomereason',
            name='call_outcome_reason_type',
            field=models.CharField(blank=True, choices=[('not_enough_information_possesed_by_patient_or_agent', 'Not Enough Information Possesed By Patient Or Agent'), ('procedure_not_offered', 'Procedure Not Offered'), ('caller_indifference', 'Caller Indifference'), ('insurance', 'Insurance'), ('pricing', 'Pricing'), ('lost', 'Lost'), ('treatment_not_offered', 'Treatment Not Offered'), ('scheduling', 'Scheduling'), ('day_or_time_not_available', 'Day Or Time Not Available'), ('too_expensive', 'Too Expensive'), ('call_interrupted', 'Call Interrupted'), ('insurance_not_taken', 'Insurance Not Taken'), ('others', 'Others'), ('not_applicable', 'Not Applicable')], db_index=True, max_length=75),
        ),
    ]
