# Generated by Django 3.2.14 on 2022-08-02 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0034_auto_20220727_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCallScoreMetricGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=120)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcallscoremetricgroup_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcallscoremetricgroup_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentCallScoreMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('payment_method', 'Payment Method'), ('patient_demographics', 'Patient Demographics'), ('Clear Well Spoken Greeting', 'Greeting'), ('Announced Name', 'Announced Name'), ('Offered Assistance', 'Offered Assistance'), ('Stated Business Name', 'Stated Business Name'), ("Asked for the Patient's Name", 'Collected Patient Name'), ("Asked for the Patient's Contact Information", 'Collected Patient Contact Info'), ("Asked for the Patient's Purpose", 'Collected Paitent Purpose'), ('Asked About Referring Source', 'Asked Referring Source'), ('Discussed Procedure Information', 'Discussed Procedure'), ('Discussed Insurance Coverage', 'Discussed Insurance Coverage'), ('Mentioned Financing / Discount Club / Payment Plans', 'Mentioned Financing'), ('Offered a Free Consultation', 'Offered Free Consultation'), ('Listened Enough (Limited Overtalk)', 'Agent Overtalk'), ('Acceptable Hold Time Length', 'Hold Time'), ('Asked About Discomfort', 'Asked About Discomfort'), ('Mentioned Pricing', 'Mentioned Pricing'), ('Offered Appointment Date / Time', 'Offered Appointment Date Time'), ('Booked the Appointment', 'Booked Appointment')], max_length=180)),
                ('metric_human_readable', models.CharField(max_length=120)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcallscoremetric_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_call_score_metrics', to='calls.agentcallscoremetricgroup')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcallscoremetric_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agentcallscore',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_call_scores', to='calls.agentcallscoremetric'),
        ),
    ]
