# Generated by Django 3.2.14 on 2022-08-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0034_auto_20220727_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCallScoreMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('GREETING', 'Clear Well Spoken Greeting'), ('ANNOUNCED_NAME', 'Announced Name'), ('OFFERED_ASSISTANCE', 'Offered Assistance'), ('STATED_BUSINESS_NAME', 'Stated Business Name'), ('ASKED_PATIENT_NAME', "Asked for the Patient's Name"), ('ASKED_PATIENT_CONTACT_INFO', "Asked for the Patient's Contact Information"), ('ASKED_PATIENT_PURPOSE', "Asked for the Patient's Purpose"), ('ASKED_REFERRING_SOURCE', 'Asked About Referring Source'), ('MENTIONED_PROCEDURE', 'Mentioned Procedure Information'), ('MENTIONED_INSURANCE_COVERAGE', 'Mentioned Insurance Coverage'), ('MENTIONED_FINANCING', 'Mentioned Financing / Discount Club / Payment Plans'), ('OFFERED_FREE_CONSULTATION', 'Offered a Free Consultation'), ('AGENT_OVERTALK', 'Listened Enough (Limited Overtalk)'), ('HOLD_TIME', 'Acceptable Hold Time Length'), ('ASKED_ABOUT_DISCOMFORT', 'Asked About Discomfort'), ('MENTIONED_PRICING', 'Mentioned Pricing'), ('OFFERED_APPOINTMENT_DATE_TIME', 'Offered Appointment Date / Time'), ('BOOKED_APPOINTMENT', 'Booked the Appointment')], max_length=180)),
                ('group', models.CharField(choices=[('Introduction', 'Intro'), ('Survey', 'Survey'), ('Selling', 'Selling'), ('Rapport', 'Rapport'), ('Convert', 'Convert')], max_length=180)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcallscoremetric_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentcallscoremetric_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agentcallscore',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_call_scores', to='calls.agentcallscoremetric'),
        ),
    ]
