# Generated by Django 3.2.14 on 2022-07-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0034_auto_20220727_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmentionedprocedure',
            name='procedure_keyword',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.procedurekeyword', to_field='keyword'),
        ),
        migrations.AlterField(
            model_name='procedurekeyword',
            name='keyword',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
