# Generated by Django 3.2.14 on 2022-08-02 01:11

from django.db import migrations

from calls.analytics.interactions.field_choices import AgentInteractionGroupType, AgentInteractionMetricTypes


# DO NOT USE THIS IN THE CODE
# THIS IS SUPPOSED TO BE CONFIGURED VIA THE RDBMS
# THIS ONLY OCCURS HERE FOR FIRST
METRIC_TO_GROUP_MAP = {
    AgentInteractionMetricTypes.GREETING: AgentInteractionGroupType.INTRO,
    AgentInteractionMetricTypes.ANNOUNCED_NAME: AgentInteractionGroupType.INTRO,
    AgentInteractionMetricTypes.OFFERED_ASSISTANCE: AgentInteractionGroupType.INTRO,
    AgentInteractionMetricTypes.STATED_BUSINESS_NAME: AgentInteractionGroupType.INTRO,

    AgentInteractionMetricTypes.COLLECTED_PATIENT_NAME: AgentInteractionGroupType.SURVEY,
    AgentInteractionMetricTypes.COLLECTED_PATIENT_CONTACT_INFO: AgentInteractionGroupType.SURVEY,
    AgentInteractionMetricTypes.COLLECTED_PATIENT_PURPOSE: AgentInteractionGroupType.SURVEY,
    AgentInteractionMetricTypes.ASKED_REFERRING_SOURCE: AgentInteractionGroupType.SURVEY,

    AgentInteractionMetricTypes.DISCUSSED_PROCEDURE: AgentInteractionGroupType.SCORE,
    AgentInteractionMetricTypes.DISCUSSED_INSURANCE_COVERAGE: AgentInteractionGroupType.SCORE,
    AgentInteractionMetricTypes.DISCUSSED_FINANCING: AgentInteractionGroupType.SCORE,
    AgentInteractionMetricTypes.OFFERED_FREE_CONSULTATION: AgentInteractionGroupType.SCORE,

    AgentInteractionMetricTypes.AGENT_OVERTALK: AgentInteractionGroupType.RAPPORT,
    AgentInteractionMetricTypes.HOLD_TIME: AgentInteractionGroupType.RAPPORT,
    AgentInteractionMetricTypes.ASKED_ABOUT_DISCOMFORT: AgentInteractionGroupType.RAPPORT,
    AgentInteractionMetricTypes.DISCUSSED_PRICING: AgentInteractionGroupType.RAPPORT,

    AgentInteractionMetricTypes.OFFERED_APPOINTMENT_DATE_TIME: AgentInteractionGroupType.CONVERT,
    AgentInteractionMetricTypes.BOOKED_APPOINTMENT: AgentInteractionGroupType.CONVERT,
}

def insert_agent_score_groups(apps, schema_editor):
    """
    We can't import the model directly as it may be a newer version than this migration expects. We use the historical version.
    """
    AgentCallScoreMetric = apps.get_model("calls", "AgentCallScoreMetric")
    for metric, group in METRIC_TO_GROUP_MAP.items():
        agent_call_score_metric, created = AgentCallScoreMetric.objects.get_or_create(metric=metric, group=group)


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0035_agent_call_score'),
    ]

    operations = [
        migrations.RunPython(insert_agent_score_groups),
    ]
