# Generated by Django 3.2.14 on 2022-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0036_add_hold_time_to_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutcomereason',
            name='call_outcome_reason_type',
            field=models.CharField(blank=True, choices=[('not_enough_information_possesed_by_patient_or_agent', 'Not enough information possessed by patient or agent to resolve'), ('procedure_not_offered', 'Procedure not offered'), ('caller_indifference', 'Caller indifference'), ('insurance', 'Insurance not taken'), ('pricing', 'Pricing'), ('lost', 'Lost'), ('treatment_not_offered', 'Treatment / procedure not offered'), ('scheduling', 'Scheduling conflict'), ('day_or_time_not_available', 'Day or time not availabe to schedule'), ('too_expensive', 'Too expensive'), ('call_interrupted', 'Call was interrupted in the middle'), ('insurance_not_taken', 'Insurance not taken'), ('others', 'Other'), ('not_applicable', 'Not Applicable'), ('incorrect_dental_code', 'Incorrect dental code'), ('incomplete_information_on_claim', 'Incomplete information on claim'), ('insurance_coverage_limit_annual', 'Insurance coverage annual limit'), ('insurance_coverage_limit_lifetime', 'Insurance coverage lifetime limit'), ('insurance_coverage_time_limit', 'Claim not submitted within plan limit'), ('insurance_incorrect_beneficiary_information', 'Incorrect beneficiary information'), ('insurance_coverage_expired', 'Insurance coverage expired'), ('insurance_coordination_of_benefits', 'Coordination of benefits'), ('insurance_preauthorization_not_obtained', 'Pre-authorization / pre-certification not obtained'), ('insurance_procedure_not_covered', 'Procedure not covered')], db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='callpurpose',
            name='call_purpose_type',
            field=models.CharField(blank=True, choices=[('new_appointment', 'New Appointment'), ('reschedule', 'Reschedule'), ('confirm_appointment', 'Confirm Appointment'), ('pricing', 'Pricing'), ('billing', 'Billing'), ('others', 'Others'), ('insurance_verification', 'Insurance Verification'), ('insurance_claim', 'Insurance Claim')], db_index=True, max_length=50),
        ),
    ]
