# Generated by Django 3.2.14 on 2022-08-07 18:07

from django.db import migrations, models

from calls.analytics.interactions.field_choices import AgentInteractionGroupType, AgentInteractionMetricTypes


# DO NOT USE THIS IN THE CODE
# THIS IS SUPPOSED TO BE CONFIGURED VIA THE RDBMS
# THIS ONLY OCCURS HERE FOR FIRST INSERT
METRIC_TO_GROUP_MAP = {
    AgentInteractionMetricTypes.ASKED_INSURANCE: AgentInteractionGroupType.RAPPORT,
    AgentInteractionMetricTypes.ASKED_BILLS: AgentInteractionGroupType.RAPPORT,
    AgentInteractionMetricTypes.CALL_LENGTH: AgentInteractionGroupType.RAPPORT,

    AgentInteractionMetricTypes.ASKED_APPOINTMENT: AgentInteractionGroupType.SELLING,
    AgentInteractionMetricTypes.CONFIRM_APPOINTMENT: AgentInteractionGroupType.SELLING,
    
}

def insert_agent_score_groups(apps, schema_editor):
    """
    We can't import the model directly as it may be a newer version than this migration expects. We use the historical version.
    """
    AgentCallScoreMetric = apps.get_model("calls", "AgentCallScoreMetric")
    for metric, group in METRIC_TO_GROUP_MAP.items():
        print(f"Inserting: {metric.name} {metric.value} {metric.label}")
        agent_call_score_metric, created = AgentCallScoreMetric.objects.get_or_create(metric=metric.value, group=group)


def reverse_insert_agent_score_groups(apps, schema_editor):
    AgentCallScoreMetric = apps.get_model("calls", "AgentCallScoreMetric")
    for metric, group in METRIC_TO_GROUP_MAP.items():
        print(f"Removing: {metric.name} {metric.value} {metric.label}")
        agent_call_score_metric = AgentCallScoreMetric.objects.get(metric=metric.value, group=group)
        agent_call_score_metric.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0039_call_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcallscoremetric',
            name='metric',
            field=models.CharField(choices=[('greeting', 'Clear Well Spoken Greeting'), ('announced_name', 'Announced Name'), ('offered_assistance', 'Offered Assistance'), ('stated_business_name', 'Stated Business Name'), ('asked_patient_name', "Asked for the Patient's Name"), ('asked_patient_contact_info', "Asked for the Patient's Contact Information"), ('asked_patient_purpose', "Asked for the Patient's Purpose"), ('asked_referring_source', 'Asked About Referring Source'), ('mentioned_procedure', 'Mentioned Procedure Information'), ('mentioned_insurance_coverage', 'Mentioned Insurance Coverage'), ('mentioned_financing', 'Mentioned Financing / Discount Club / Payment Plans'), ('offered_free_consultation', 'Offered a Free Consultation'), ('agent_overtalk', 'Listened Enough (Limited Overtalk)'), ('hold_time', 'Acceptable Hold Time Length'), ('asked_about_discomfort', 'Asked About Discomfort'), ('mentioned_pricing', 'Mentioned Pricing'), ('offered_appointment_date_time', 'Offered Appointment Date / Time'), ('booked_appointment', 'Booked the Appointment'), ('asked_insurance', 'Asked about / verified insurance'), ('asked_bills', 'Asked about outstanding bills / balances'), ('call_length', 'Off the phone quickly'), ('asked_appointment', 'Asked about appointment'), ('confirm_appointment', 'Confirmed / retained appointment')], max_length=180),
        ),
        migrations.RunPython(insert_agent_score_groups, reverse_insert_agent_score_groups),
    ]
