# Generated by Django 3.2.14 on 2022-08-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0040_outbound_score_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcallscoremetric',
            name='metric',
            field=models.CharField(choices=[('greeting', 'Clear Well Spoken Greeting'), ('announced_name', 'Announced Name'), ('offered_assistance', 'Offered Assistance'), ('stated_business_name', 'Stated Business Name'), ('asked_patient_name', "Asked for the Patient's Name"), ('asked_patient_contact_info', "Asked for the Patient's Contact Information"), ('asked_patient_purpose', "Asked for the Patient's Purpose"), ('asked_referring_source', 'Asked About Referring Source'), ('mentioned_procedure', 'Mentioned Procedure Information'), ('mentioned_insurance_coverage', 'Mentioned Insurance Coverage'), ('mentioned_financing', 'Mentioned Financing / Discount Club / Payment Plans'), ('offered_free_consultation', 'Offered a Free Consultation'), ('agent_overtalk', 'Listened Enough (Limited Overtalk)'), ('hold_time', 'Acceptable Hold Time Length'), ('asked_about_discomfort', 'Asked About Discomfort'), ('mentioned_pricing', 'Mentioned Pricing'), ('offered_appointment_date_time', 'Offered Appointment Date / Time'), ('booked_appointment', 'Booked the Appointment'), ('asked_insurance', 'Asked about / verified insurance'), ('asked_bills', 'Asked about outstanding bills / balances'), ('call_length', 'Off the phone quickly'), ('asked_appointment', 'Asked about appointment'), ('confirm_appointment', 'Confirmed / retained appointment'), ('provided_patient_name', 'Provided patient name'), ('provided_patient_insurance_ids', 'Provided patient insurance ids '), ('provided_patient_date_of_birth', 'Provided patient date of birth'), ('provided_social_security_number', 'Provided Social Security Number'), ('asked_policy_active', 'Asked policy active / effective date'), ('asked_policy_expiration_date', 'Asked policy expiration date'), ('asked_authorization_requirements', 'Asked authorization requirements')], max_length=180),
        ),
        migrations.AlterField(
            model_name='callpurpose',
            name='call_purpose_type',
            field=models.CharField(blank=True, choices=[('new_appointment', 'New Appointment'), ('reschedule', 'Reschedule'), ('confirm_appointment', 'Confirm Appointment'), ('pricing', 'Pricing'), ('billing', 'Billing'), ('others', 'Others'), ('insurance_authorization', 'Insurance Authorization'), ('insurance_verification', 'Insurance Verification'), ('insurance_claim', 'Insurance Claim')], db_index=True, max_length=50),
        ),
    ]
