# Generated by Django 3.2.14 on 2022-08-08 05:05

from django.db import migrations, models

from calls.analytics.interactions.field_choices import AgentInteractionGroupType, AgentInteractionMetricTypes


# DO NOT USE THIS IN THE CODE
# THIS IS SUPPOSED TO BE CONFIGURED VIA THE RDBMS
# THIS ONLY OCCURS HERE FOR FIRST INSERT
METRIC_TO_GROUP_MAP = {
    AgentInteractionMetricTypes.PROVIDED_PATIENT_NAME: AgentInteractionGroupType.PROVIDE,
    AgentInteractionMetricTypes.PROVIDED_PATIENT_INSURANCE_IDS: AgentInteractionGroupType.PROVIDE,
    AgentInteractionMetricTypes.PROVIDED_PATIENT_DATE_OF_BIRTH: AgentInteractionGroupType.PROVIDE,
    AgentInteractionMetricTypes.PROVIDED_SOCIAL_SECURITY_NUMBER: AgentInteractionGroupType.PROVIDE,

    AgentInteractionMetricTypes.ASKED_POLICY_ACTIVE: AgentInteractionGroupType.SURVEY,
    AgentInteractionMetricTypes.ASKED_POLICY_EXPIRATION_DATE: AgentInteractionGroupType.SURVEY,
    AgentInteractionMetricTypes.ASKED_AUTHORIZATION_REQUIREMENTS: AgentInteractionGroupType.SURVEY,
}

def insert_agent_score_groups(apps, schema_editor):
    """
    We can't import the model directly as it may be a newer version than this migration expects. We use the historical version.
    """
    AgentCallScoreMetric = apps.get_model("calls", "AgentCallScoreMetric")
    for metric, group in METRIC_TO_GROUP_MAP.items():
        print(f"Inserting: {metric.name} {metric.value} {metric.label}")
        agent_call_score_metric, created = AgentCallScoreMetric.objects.get_or_create(metric=metric.value, group=group)


def reverse_insert_agent_score_groups(apps, schema_editor):
    AgentCallScoreMetric = apps.get_model("calls", "AgentCallScoreMetric")
    for metric, group in METRIC_TO_GROUP_MAP.items():
        print(f"Removing: {metric.name} {metric.value} {metric.label}")
        agent_call_score_metric = AgentCallScoreMetric.objects.get(metric=metric.value, group=group)
        agent_call_score_metric.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0041_outbound_insurance_metrics_iteration_2'),
    ]

    operations = [
        migrations.RunPython(insert_agent_score_groups, reverse_insert_agent_score_groups),
    ]
