# Generated by Django 3.2.14 on 2022-08-08 18:20

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0042_outbound_insurance_metrics_iteration_2_insert'),
    ]

    operations = [
        BtreeGinExtension(),
    ]
