# Generated by Django 3.2.14 on 2022-08-08 18:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0043_gin_extension_installation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltranscript',
            options={},
        ),
        migrations.AddField(
            model_name='calltranscript',
            name='transcript_text_full',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='agentcallscoremetric',
            name='group',
            field=models.CharField(choices=[('introduction', 'Intro'), ('survey', 'Survey'), ('selling', 'Selling'), ('rapport', 'Rapport'), ('convert', 'Convert'), ('provide', 'Provide')], max_length=180),
        ),
        migrations.AddIndex(
            model_name='calltranscript',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcript_text_full'], name='calls_callt_transcr_bb31a8_gin'),
        ),
    ]
