# Generated by Django 3.2.14 on 2022-08-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0043_gin_extension_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcallscoremetric',
            name='group',
            field=models.CharField(choices=[('introduction', 'Intro'), ('survey', 'Survey'), ('selling', 'Selling'), ('rapport', 'Rapport'), ('convert', 'Convert'), ('provide', 'Provide')], max_length=180),
        ),
    ]
