# Generated by Django 3.2.14 on 2022-08-11 19:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0044_agentcallscoregroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltranscript',
            options={},
        ),
        migrations.AddField(
            model_name='calltranscript',
            name='transcript_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calltranscript',
            name='transcript_text_tsvector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
