# Generated by Django 3.2.15 on 2022-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0046_transcript_text_tsvector_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentengagedwith',
            name='raw_non_agent_engagement_persona_model_run_id',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
