# Generated by Django 3.2.14 on 2022-08-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0047_alter_agentengagedwith_raw_non_agent_engagement_persona_model_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsentiment',
            name='raw_call_sentiment_model_run_id',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
