# Generated by Django 3.2.15 on 2022-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0048_call_sentiment_raw_model_id_must_be_blankable'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='sip_callee_extension',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='call',
            name='sip_caller_extension',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
