# Generated by Django 3.2.15 on 2022-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0049_sip_extensions_for_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
