# Generated by Django 3.2.15 on 2022-09-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0050_unique_assigned_agent_and_agent_engaged_with"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calloutcome",
            name="call_purpose",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outcome_results",
                to="calls.callpurpose",
                unique=True,
                verbose_name="The source purpose for this outcome",
            ),
        ),
    ]
