# Generated by Django 3.2.15 on 2022-09-24 00:44
import logging
from collections import defaultdict

from django.db import migrations

# Get an instance of a logger
log = logging.getLogger(__name__)


def deduplicate_purposes(apps, schema_editor):
    """
    We can't import the model directly as it may be a newer version than this migration expects. We use the historical version.
    """

    Call = apps.get_model("calls", "Call")
    calls = Call.objects.all().prefetch_related("call_purposes")

    cps_removed = []
    for call in calls:
        log.info(call)
        if not hasattr(call, "call_purposes"):
            log.info(f"Ignoring call that has no purposes: {call.id}")
            continue

        # slice by type
        # TODO: order by modified_at
        # slice every non-first element
        # iterate and delete
        # TODO: delete call_outcomes
        # TODO: delete call_outcome_reasons

        purpose_type_to_purpose = defaultdict(list)
        for cp in call.call_purposes.all():
            purpose_type_to_purpose[cp.call_purpose_type].append(cp)

        log.info(purpose_type_to_purpose)
        for _, cps in purpose_type_to_purpose.items():
            cps_to_remove = cps[1:]
            for cp in cps_to_remove:
                cp_id = cp.id
                log.info(f"Deleting duplicate call_purpose with id='{cp_id}' type={cp.call_purpose_type}")
                cp.delete()
                cps_removed.append(cp_id)

    log.info(f"Deleted duplicate call_purpose records with ids: {cps_removed}")


def reduplicate_purposes(apps, schema_editor):
    """Impossible to do unless we're storing the duplicates in a temporary table."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0052_outcome_unique_per_purpose"),
    ]

    operations = [
        migrations.RunPython(deduplicate_purposes, reduplicate_purposes),
    ]
