# Generated by Django 3.2.15 on 2022-09-24 00:44
import logging

from django.db import migrations

# Get an instance of a logger
log = logging.getLogger(__name__)


def deduplicate_purposes(apps, schema_editor):
    """
    We can't import the model directly as it may be a newer version than this migration expects. We use the historical version.
    """

    Call = apps.get_model("calls", "Call")
    calls = Call.objects.all().prefetch_related("call_purposes")

    cps_removed = []
    for call in calls:
        if not hasattr(call, "call_purposes"):
            log.info(f"Ignoring call that has no purposes: {call.id}")
            continue

            # TODO: implement

    log.info(f"Deleted duplicate call_purpose records with ids: {cos_removed}")


def reduplicate_purposes(apps, schema_editor):
    """Impossible to do unless we're storing the duplicates in a temporary table."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0052_outcome_unique_per_purpose"),
    ]

    operations = [
        migrations.RunPython(deduplicate_purposes, reduplicate_purposes),
    ]
