# Generated by Django 3.2.15 on 2022-09-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0053_purpose_deduplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callpurpose",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="callpurpose",
            unique_together={("call", "call_purpose_type")},
        ),
    ]
