# Generated by Django 3.2.15 on 2022-09-30 14:36

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # HEREBEDRAGONS: Indexes added concurrently cannot happen in-transaction
    atomic = False

    dependencies = [
        ("calls", "0054_purpose_unique_call_and_purpose_type"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="call",
            index=models.Index(fields=["sip_callee_extension"], name="sip_callee_extension_idx"),
        ),
        AddIndexConcurrently(
            model_name="call",
            index=models.Index(fields=["sip_callee_number"], name="sip_callee_number_idx"),
        ),
        AddIndexConcurrently(
            model_name="call",
            index=models.Index(fields=["sip_caller_extension"], name="sip_caller_extension_idx"),
        ),
        AddIndexConcurrently(
            model_name="call",
            index=models.Index(fields=["sip_caller_number"], name="sip_caller_number_idx"),
        ),
    ]
