# Generated by Django 3.2.15 on 2022-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0055_auto_20220930_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
