# Generated by Django 3.2.15 on 2022-10-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0055_auto_20220930_1454'),
        ('calls', '0056_nullable_call_end_time'),
    ]

    operations = [
    ]
