# Generated by Django 3.2.15 on 2022-10-10 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0057_merge_20221005_0047"),
    ]

    #
    # I did not include code to remove duplicates. This migration assumes that duplicates have been removed in an environment. I've already done this in all
    # environments. This also means that your local envioronment may need to besimilarly cleaned-up manually.
    #
    operations = [
        migrations.AlterField(
            model_name="callsentiment",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_sentiments",
                to="calls.call",
                unique=True,
                verbose_name="Sentiment score of the call",
            ),
        ),
    ]
