# Generated by Django 3.2.16 on 2022-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0059_transcript_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callmentionedcompany",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedinsurance",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedprocedure",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedproduct",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedsymptom",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="callpurpose",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="callmentionedcompany",
            constraint=models.UniqueConstraint(fields=("call", "keyword"), name="unique mentioned company keyword to call assignment"),
        ),
        migrations.AddConstraint(
            model_name="callmentionedinsurance",
            constraint=models.UniqueConstraint(fields=("call", "keyword"), name="unique keyword to call assignment"),
        ),
        migrations.AddConstraint(
            model_name="callmentionedprocedure",
            constraint=models.UniqueConstraint(fields=("call", "keyword"), name="unique mentioned procedure keyword to call assignment"),
        ),
        migrations.AddConstraint(
            model_name="callmentionedproduct",
            constraint=models.UniqueConstraint(fields=("call", "keyword"), name="unique mentioned product keyword to call assignment"),
        ),
        migrations.AddConstraint(
            model_name="callmentionedsymptom",
            constraint=models.UniqueConstraint(fields=("call", "keyword"), name="unique mentioned symptom keyword to call assignment"),
        ),
        migrations.AddConstraint(
            model_name="callpurpose",
            constraint=models.UniqueConstraint(fields=("call", "call_purpose_type"), name="unique call_purpose_type to call assignment"),
        ),
    ]
