# Generated by Django 3.2.16 on 2022-12-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0059_transcript_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callmentionedcompany",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedinsurance",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedprocedure",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedproduct",
            options={},
        ),
        migrations.AlterModelOptions(
            name="callmentionedsymptom",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="callmentionedcompany",
            unique_together={("call", "keyword")},
        ),
        migrations.AlterUniqueTogether(
            name="callmentionedinsurance",
            unique_together={("call", "keyword")},
        ),
        migrations.AlterUniqueTogether(
            name="callmentionedprocedure",
            unique_together={("call", "keyword")},
        ),
        migrations.AlterUniqueTogether(
            name="callmentionedproduct",
            unique_together={("call", "keyword")},
        ),
        migrations.AlterUniqueTogether(
            name="callmentionedsymptom",
            unique_together={("call", "keyword")},
        ),
    ]
