# Generated by Django 3.2.16 on 2023-01-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0060_mentioned_keyword_unique_per_call__purpose_type_unique_per_call_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="telecomcallernameinfo",
            name="is_known_insurance_provider",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
