# Generated by Django 3.2.16 on 2023-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0061_telecomcallernameinfo_is_known_insurance_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calltranscript",
            name="transcript_type",
            field=models.CharField(
                choices=[
                    ("full_text", "Full Text"),
                    ("channel_1_text", "Channel 1 Text"),
                    ("channel_2_text", "Channel 2 Text"),
                    ("speaker_1_text", "Speaker 1 Text"),
                    ("speaker_2_text", "Speaker 2 Text"),
                ],
                db_index=True,
                default="full_text",
                max_length=80,
            ),
        ),
    ]
