# Generated by Django 3.2.10 on 2021-12-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeloxExtractData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField()),
                ('pms_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guarantor_id', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('mobile_phone', models.IntegerField()),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(max_length=255)),
            ],
        ),
    ]
