# Generated by Django 3.2.10 on 2021-12-17 17:49

from django.db import migrations, models
import django_extensions.db.fields
import etl.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeloxExtractData',
            fields=[
                ('velox_id', models.IntegerField(primary_key=True, serialize=False)),
                ('peerlogic_id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False)),
                ('deleted', models.BooleanField()),
                ('pms_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guarantor_id', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('mobile_phone', models.IntegerField()),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField()),
                ('velox_extract_data', models.JSONField(default=etl.models.VeloxExtractData.velox_extract_data_default)),
            ],
        ),
    ]
