# Generated by Django 3.2.10 on 2021-12-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veloxpatientextract',
            name='peerlogic_patient_id',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
    ]
