# Generated by Django 3.2.11 on 2022-01-18 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veloxpatientextract',
            name='peerlogic_patient_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=22),
        ),
        migrations.CreateModel(
            name='NetsapiensCdrsExtract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('netsapiens_callid', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('peerlogic_call_id', models.CharField(blank=True, db_index=True, default='', max_length=22)),
                ('netsapiens_cdrs_extract', models.JSONField(default=dict, help_text='CDRs')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netsapienscdrsextract_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netsapienscdrsextract_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
