# Generated by Django 3.2.11 on 2022-01-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_netsapiens_etl_and_db_indices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetsapiensCdrsExtract',
        ),
    ]
