steps:
- id: "Store environment variables in .env"
  name: ubuntu
  entrypoint: bash
  args:
    - -c
    - |
      # Save env vars to persistent volume mount: "/workspace"
      echo -e 'BANDWIDTH_API_PASSWORD=$$BANDWIDTH_API_PASSWORD' >> /workspace/.env &&
      echo -e 'BANDWIDTH_API_USERNAME=$_BANDWIDTH_API_USERNAME' >> /workspace/.env &&
      echo -e 'BANDWIDTH_APPLICATION_ID=$_BANDWIDTH_APPLICATION_ID' >> /workspace/.env &&
      echo -e 'BANDWIDTH_MESSAGING_URI=$_BANDWIDTH_MESSAGING_URI' >> /workspace/.env &&
      echo -e 'CELERY_BROKER_URL=$_CELERY_BROKER_URL' >> /workspace/.env &&
      echo -e 'CELERY_RESULT_BACKEND=$_CELERY_RESULT_BACKEND' >> /workspace/.env &&
      echo -e 'DJANGO_ALLOWED_HOSTS=$_DJANGO_ALLOWED_HOSTS' >> /workspace/.env &&
      echo -e 'DJANGO_DB_REQUIRE_SSL=$_DJANGO_DB_REQUIRE_SSL' >> /workspace/.env &&
      echo -e 'DJANGO_DEBUG=$_DJANGO_DEBUG' >> /workspace/.env &&
      echo -e 'DJANGO_EMAIL_BACKEND=$_DJANGO_EMAIL_BACKEND' >> /workspace/.env &&
      echo -e 'DJANGO_SECRET_KEY=$$DJANGO_SECRET_KEY' >> /workspace/.env &&
      echo -e 'NETSAPIENS_ACCESS_TOKEN_URL=$_NETSAPIENS_ACCESS_TOKEN_URL' >> /workspace/.env &&
      echo -e 'NETSAPIENS_API_PASSWORD=$$NETSAPIENS_API_PASSWORD' >> /workspace/.env &&
      echo -e 'NETSAPIENS_API_USERNAME=$_NETSAPIENS_API_USERNAME' >> /workspace/.env &&
      echo -e 'NETSAPIENS_BASE_URL=$_NETSAPIENS_BASE_URL' >> /workspace/.env &&
      echo -e 'NETSAPIENS_CLIENT_ID=$_NETSAPIENS_CLIENT_ID' >> /workspace/.env &&
      echo -e 'NETSAPIENS_CLIENT_SECRET=$$NETSAPIENS_CLIENT_SECRET' >> /workspace/.env &&
      echo -e 'NETSAPIENS_INTROSPECT_TOKEN_URL=$_NETSAPIENS_INTROSPECT_TOKEN_URL' >> /workspace/.env &&
      echo -e 'ENVIRONMENT=$_ENVIRONMENT' >> /workspace/.env &&
      echo -e 'PAGE_SIZE=$_PAGE_SIZE' >> /workspace/.env &&
      echo -e 'POSTGRES_DB=$_POSTGRES_DB' >> /workspace/.env &&
      echo -e 'POSTGRES_PASSWORD=$$POSTGRES_PASSWORD' >> /workspace/.env
      echo -e 'POSTGRES_USER=$_POSTGRES_USER' >> /workspace/.env &&
  secretEnv:
    - "BANDWIDTH_API_PASSWORD"
    - "DJANGO_SECRET_KEY"
    - "NETSAPIENS_CLIENT_SECRET"
    - "NETSAPIENS_API_PASSWORD"
    - "POSTGRES_PASSWORD"

- id: "Validate the .env exists"
  name: ubuntu
  args: ["ls", "-lah", "/workspace/src/"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ['-q','app', 'deploy', '/workspace/deployment/app_engine/app.yaml']
  dir: '.'
  timeout: "1600s"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/BANDWIDTH_API_PASSWORD/versions/latest
    env: "BANDWIDTH_API_PASSWORD"
  - versionName: projects/$PROJECT_NUMBER/secrets/DJANGO_SECRET_KEY/versions/latest
    env: "DJANGO_SECRET_KEY"
  - versionName: projects/$PROJECT_NUMBER/secrets/NETSAPIENS_API_PASSWORD/versions/latest
    env: "NETSAPIENS_API_PASSWORD"
  - versionName: projects/$PROJECT_NUMBER/secrets/NETSAPIENS_CLIENT_SECRET/versions/latest
    env: "NETSAPIENS_CLIENT_SECRET"
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_PASSWORD/versions/latest
    env: "POSTGRES_PASSWORD"