steps:
- id: Copy requirements.txt to root of directory for app engine to see
  name: "ubuntu"
  entrypoint: "cp"
  args: ["/workspace/requirements/requirements.txt", "/workspace/requirements.txt"]
  timeout: "1600s"

- id: Copy app engine modules to root of directory for app engine to see
  name: "ubuntu"
  entrypoint: "cp"
  args: ["-R", "/workspace/deployment/app_engine/*", "/workspace/."]
  timeout: "1600s"

- id: "Validate the workspace looks right"
  name: ubuntu
  args: ["ls", "-lah", "/workspace/"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', '/workspace/app.yaml']
  timeout: "1600s"
