
- id: Copy requirements.txt to root of directory for app engine to see
  name: "ubuntu"
  entrypoint: "cp"
  args: ["/workspace/", "/workspace/requirements.txt"]
  timeout: "1600s"

- id: Copy app engine modules to root of directory for app engine to see
  name: "ubuntu"
  entrypoint: "cp"
  args: ["-R", "/workspace/deployment/app_engine/*", "/workspace/."]
  timeout: "1600s"

- id: "Validate the workspace looks right"
  name: ubuntu
  args: ["ls", "-lah", "/workspace/"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', '/workspace/app.yaml']
  timeout: "1600s"

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/BANDWIDTH_API_PASSWORD/versions/latest
    env: "BANDWIDTH_API_PASSWORD"
  - versionName: projects/$PROJECT_NUMBER/secrets/DJANGO_SECRET_KEY/versions/latest
    env: "DJANGO_SECRET_KEY"
  - versionName: projects/$PROJECT_NUMBER/secrets/NETSAPIENS_API_PASSWORD/versions/latest
    env: "NETSAPIENS_API_PASSWORD"
  - versionName: projects/$PROJECT_NUMBER/secrets/NETSAPIENS_CLIENT_SECRET/versions/latest
    env: "NETSAPIENS_CLIENT_SECRET"
  - versionName: projects/$PROJECT_NUMBER/secrets/POSTGRES_PEERLOGIC_PASSWORD/versions/latest
    env: "POSTGRES_PEERLOGIC_PASSWORD"