# Generated by Django 3.2.13 on 2022-06-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_merge_20220617_leaf_node_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('cadence_type', models.CharField(choices=[('night_before', 'Night before'), ('morning_of', 'Morning of')], max_length=40)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadence_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('user_telecom_sending_reminder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadences', to='core.usertelecom', verbose_name='The telecom user that is sending the reminder')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
