# Generated by Django 3.2.16 on 2023-01-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexhealth_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
