# Generated by Django 3.2.16 on 2023-01-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20230104_1513"),
        ("nexhealth_integration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="phone_number_best",
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="nexhealthpatientlink",
            name="peerlogic_patient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nexhealth_patient", to="core.patient"),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="fee_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
