# Generated by Django 3.2.16 on 2023-01-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20230104_2213"),
        ("nexhealth_integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NexHealthAppointmentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nh_institution_id", models.PositiveIntegerField(db_index=True)),
                ("nh_appointment_id", models.PositiveIntegerField(db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="nexhealthpatientlink",
            name="unique_nexhealth_patient_with_peerlogic_patient",
        ),
        migrations.RemoveField(
            model_name="nexhealthpatientlink",
            name="nh_location_id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone_number_best",
        ),
        migrations.AddField(
            model_name="institution",
            name="synced_patients_to_peerlogic_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="synced_appointments_to_peerlogic_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="nexhealthpatientlink",
            name="peerlogic_patient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nexhealth_patient", to="core.patient"),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="fee_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddConstraint(
            model_name="nexhealthpatientlink",
            constraint=models.UniqueConstraint(
                fields=("nh_institution_id", "nh_patient_id", "peerlogic_patient_id"), name="unique_nexhealth_patient_with_peerlogic_patient"
            ),
        ),
        migrations.AddField(
            model_name="nexhealthappointmentlink",
            name="peerlogic_appointment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nexhealth_appointment", to="core.appointment"),
        ),
        migrations.AddConstraint(
            model_name="nexhealthappointmentlink",
            constraint=models.UniqueConstraint(
                fields=("nh_institution_id", "nh_appointment_id", "peerlogic_appointment_id"), name="unique_nexhealth_appointment_with_peerlogic_appointment"
            ),
        ),
    ]
