# Generated by Django 3.2.16 on 2023-01-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0004_auto_20230120_2024"),
        ("nexhealth_integration", "0002_auto_20230104_2213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nexhealthappointmentlink",
            name="peerlogic_appointment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nexhealth_appointment", to="care.appointment"),
        ),
        migrations.AlterField(
            model_name="nexhealthpatientlink",
            name="peerlogic_patient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="nexhealth_patient", to="care.patient"),
        ),
    ]
