# Generated by Django 3.2.13 on 2022-06-02 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_voipprovider_integration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiveCallPartial',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('external_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JiveChannel',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, unique=True)),
                ('external_id', models.CharField(max_length=256, unique=True)),
                ('signature', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JiveSession',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jive_integration.jivechannel')),
            ],
        ),
        migrations.CreateModel(
            name='JiveLine',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('source_jive_id', models.CharField(max_length=64, unique=True)),
                ('source_organization_jive_id', models.CharField(max_length=64, unique=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jive_integration.jivesession')),
            ],
        ),
        migrations.CreateModel(
            name='JiveConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(blank=True)),
                ('last_sync', models.DateTimeField(default='0001-01-01T00:00:00')),
                ('active', models.BooleanField(default=True, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jiveconnection_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jiveconnection_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('practice_telecom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.practicetelecom')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jivechannel',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jive_integration.jiveconnection'),
        ),
    ]
