# Generated by Django 3.2.16 on 2022-11-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jive_integration', '0013_jive_api_credentials_additional_fields'),
    ]

    operations = [
        migrations.RenameField('JiveAWSRecordingBucket', 'connection', 'bar'),
        migrations.RenameField('JiveChannel', 'connection', 'bar')
    ]
