# Generated by Django 3.2.16 on 2022-11-04 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jive_integration', '0003_jivesubscriptioneventextract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiveCallPartial',
        ),
    ]
