# Generated by Django 3.2.16 on 2022-11-05 23:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jive_integration', '0005_relate_jive_channel_to_extracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiveAWSRecordingBucket',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('access_key_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('username', models.CharField(blank=True, max_length=64, unique=True)),
                ('policy_arn', models.CharField(blank=True, max_length=2048, unique=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jive_integration.jiveconnection')),
            ],
        ),
    ]
