# Generated by Django 3.2.16 on 2022-11-05 20:07

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jive_integration', '0005_relate_jive_channel_to_extracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiveAWSRecordingBucket',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('access_key_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('secret_access_key', models.CharField(blank=True, max_length=256, unique=True)),
                ('bucket_name', models.CharField(blank=True, max_length=63)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jive_integration.jiveconnection')),
            ],
        ),
    ]
