# Generated by Django 3.2.16 on 2022-11-09 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jive_integration', '0007_bucket_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiveconnection',
            name='account_key',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jiveconnection',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jiveconnection',
            name='organizer_key',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jiveconnection',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jiveawsrecordingbucket',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jive_integration.jiveconnection'),
        ),
    ]
