apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  variant: dev

bases:
- ../../base

patchesStrategicMerge:
 - configmap.yaml
 - cloudsql.yaml
 - peerlogic-api-deployment.yaml
 - ssl.yaml