# Generated by Django 3.2.15 on 2022-09-17 15:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RingCentralSessionEvent',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sequence', models.IntegerField(default=None, null=True)),
                ('session_id', models.CharField(max_length=255)),
                ('telephony_session_id', models.CharField(max_length=255)),
                ('server_id', models.CharField(max_length=255)),
                ('event_time', models.DateTimeField()),
                ('to_name', models.CharField(max_length=255, null=True)),
                ('to_extension_id', models.CharField(max_length=255, null=True)),
                ('to_phone_number', models.CharField(max_length=255, null=True)),
                ('from_name', models.CharField(max_length=255, null=True)),
                ('from_extension_id', models.CharField(max_length=255, null=True)),
                ('from_phone_number', models.CharField(max_length=255, null=True)),
                ('muted', models.BooleanField(default=False)),
                ('status_rcc', models.BooleanField(default=False)),
                ('status_code', models.CharField(max_length=255)),
                ('status_reason', models.CharField(max_length=255, null=True)),
                ('account_id', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('missed_call', models.BooleanField(default=False)),
                ('stand_alone', models.BooleanField(default=False)),
                ('full_session_event', models.JSONField(default=dict)),
            ],
        ),
    ]
