# Generated by Django 3.2.15 on 2022-09-20 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20220920_1153'),
        ('ringcentral_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingCentralAPICredentials',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('api_url', models.CharField(blank=True, max_length=2048)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('client_secret', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=63)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=False, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ringcentralapicredentials_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ringcentralapicredentials_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('voip_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voipprovider')),
            ],
            options={
                'verbose_name_plural': 'RingCentralAPICredentials',
            },
        ),
    ]
