# Generated by Django 3.2.15 on 2022-10-05 00:01

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ringcentral_integration', '0002_ringcentralapicredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingCentralCallLeg',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('peerlogic_call_id', models.CharField(blank=True, db_index=True, default='', max_length=22)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('delegate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delegate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(default=None, null=True)),
                ('extension_id', models.CharField(blank=True, max_length=255, null=True)),
                ('extension_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('leg_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_description', models.CharField(blank=True, max_length=255, null=True)),
                ('to_name', models.CharField(max_length=255, null=True)),
                ('to_extension_id', models.CharField(max_length=255, null=True)),
                ('to_phone_number', models.CharField(max_length=255, null=True)),
                ('from_name', models.CharField(max_length=255, null=True)),
                ('from_extension_id', models.CharField(max_length=255, null=True)),
                ('from_phone_number', models.CharField(max_length=255, null=True)),
                ('transport', models.CharField(blank=True, max_length=255, null=True)),
                ('recording', models.CharField(blank=True, db_index=True, default='', max_length=22)),
                ('master', models.BooleanField(default=False)),
                ('message_type', models.CharField(max_length=255, null=True)),
                ('telephony_session_id', models.CharField(max_length=255, null=True)),
                ('internal_type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
