# Generated by Django 3.2.15 on 2022-10-07 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20221005_0001'),
        ('ringcentral_integration', '0003_ringcentralcallleg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingCentralCallSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(blank=True, default='', help_text="Subscription ID for RingCentral on the Voip Provider's side. The source of the data / events", max_length=32)),
                ('active', models.BooleanField(default=True, null=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ringcentralcallsubscription_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ringcentralcallsubscription_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('practice_telecom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.practicetelecom')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
