# Generated by Django 3.2.12 on 2022-04-05 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0023_callprocedurediscussed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(blank=True, choices=[('new_patient_opportunity', 'New Patient Opportunity'), ('call_purpose', 'Call Purpose'), ('call_outcome', 'Call Outcome'), ('call_outcome_reason', 'Call Outcome Reason'), ('call_sentiment_transcript', 'Call Transcript Sentiment'), ('call_transcript_fragment_sentiment', 'Call Transcript Fragment Sentiment'), ('call_audio_enthusiasm', 'Call Audio Enthusiasm')], db_index=True, max_length=100)),
                ('model_version', models.CharField(max_length=64)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlmodel_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlmodel_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLModelResultHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=22)),
                ('label', models.CharField(max_length=150)),
                ('score', models.FloatField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_model_results', to='calls.call', verbose_name='model results from the call')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlmodelresulthistory_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_results', to='ml.mlmodel', verbose_name='model results from the model runs')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlmodelresulthistory_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
