# Generated by Django 3.2.12 on 2022-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='hyper_parameters',
            field=models.JSONField(null=True),
        ),
    ]
