# Generated by Django 3.2.12 on 2022-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_mlmodel_hyper_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(blank=True, choices=[('new_patient_opportunity', 'New Patient Opportunity'), ('call_purpose', 'Call Purpose'), ('call_outcome', 'Call Outcome'), ('call_outcome_reason', 'Call Outcome Reason'), ('call_transcript_sentiment', 'Call Transcript Sentiment'), ('call_transcript_fragment_sentiment', 'Call Transcript Fragment Sentiment'), ('call_audio_enthusiasm', 'Call Audio Enthusiasm')], db_index=True, max_length=100),
        ),
    ]
