# Generated by Django 3.2.12 on 2022-04-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_mlmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='vertex_deployed_model_id',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
