# Generated by Django 3.2.12 on 2022-04-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_mlmodel_vertex_deployed_model_id'),
    ]

    operations = [

        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_type',
            new_name='classification_domain',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='classification_domain',
            field=models.CharField(choices=[('new_patient_opportunity', 'New Patient Opportunity'), ('caller_type', 'Caller Type'), ('call_purpose', 'Call Purpose'), ('call_outcome', 'Call Outcome'), ('call_outcome_reason', 'Call Outcome Reason'), ('call_transcript_sentiment', 'Call Transcript Sentiment'), ('call_transcript_fragment_sentiment', 'Call Transcript Fragment Sentiment'), ('call_audio_enthusiasm', 'Call Audio Enthusiasm')], db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mlmodelresulthistory',
            name='classification_domain',
            field=models.CharField(choices=[('new_patient_opportunity', 'New Patient Opportunity'), ('caller_type', 'Caller Type'), ('call_purpose', 'Call Purpose'), ('call_outcome', 'Call Outcome'), ('call_outcome_reason', 'Call Outcome Reason'), ('call_transcript_sentiment', 'Call Transcript Sentiment'), ('call_transcript_fragment_sentiment', 'Call Transcript Fragment Sentiment'), ('call_audio_enthusiasm', 'Call Audio Enthusiasm')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='vertex_deployed_model_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodelresulthistory',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_results', to='ml.mlmodel', verbose_name='model results from the model runs'),
        ),
        migrations.AlterField(
            model_name='mlmodelresulthistory',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
