# Generated by Django 3.2.16 on 2022-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0005_auto_20220411_1912"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodelresulthistory",
            name="threshold",
            field=models.FloatField(null=True),
        ),
    ]
