# Generated by Django 3.2.16 on 2022-11-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0006_mlmodelresulthistory_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodelresulthistory",
            name="label",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="mlmodelresulthistory",
            name="run_id",
            field=models.CharField(db_index=True, max_length=22),
        ),
        migrations.AlterField(
            model_name="mlmodelresulthistory",
            name="score",
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="mlmodelresulthistory",
            name="threshold",
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
