apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: peerlogic-api-ssl

patchesStrategicMerge:
- |-
  apiVersion: networking.gke.io/v1
  kind: ManagedCertificate
  metadata:
    name: peerlogic-tech
    env: prod
  spec:
    domains:
      - api-prod.peerlogic.tech

patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: basic-ingress
    annotations:
      kubernetes.io/ingress.global-static-ip-name: peerlogic-api-prod
      networking.gke.io/managed-certificates: api-prod-peerlogic-tech
  
resources:
- ssl.yaml