# Generated by Django 3.2.11 on 2022-01-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_voipprovider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netsapiens_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetsapiensAPICredentials',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('authentication_url', models.CharField(blank=True, max_length=2048)),
                ('call_subscription_url', models.CharField(blank=True, max_length=2048)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('client_secret', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=63)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netsapiensapicredentials_created', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netsapiensapicredentials_modified', to=settings.AUTH_USER_MODEL, verbose_name='The user that is automatically assigned')),
                ('voip_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voipprovider')),
            ],
            options={
                'get_latest_by': 'modified_at',
                'abstract': False,
            },
        ),
    ]
