# Generated by Django 3.2.11 on 2022-01-25 20:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0002_create_cdr2_model_and_alter_fields_db_indices_and_null_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetsapiensCall',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('peerlogic_call_id', models.CharField(blank=True, db_index=True, default='', max_length=22)),
            ],
        ),
        migrations.AddField(
            model_name='netsapienscdr2extract',
            name='netsapiens_call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netsapiens_integration.netsapienscall'),
        ),
    ]
