# Generated by Django 3.2.11 on 2022-01-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0002_netsapiens_api_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsapiensapicredentials',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
