# Generated by Django 3.2.11 on 2022-01-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0002_create_cdr2_model_and_alter_fields_db_indices_and_null_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsapienscdr2extract',
            name='peerlogic_call_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=22),
        ),
    ]
