# Generated by Django 3.2.11 on 2022-01-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0004_netsapiens_api_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netsapiensapicredentials',
            old_name='authentication_url',
            new_name='api_url',
        ),
    ]
