# Generated by Django 3.2.11 on 2022-01-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0005_change_auth_url_to_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netsapiensapicredentials',
            name='call_subscription_url',
        ),
    ]
