# Generated by Django 3.2.11 on 2022-01-27 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_voip_provider_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netsapiens_integration', '0006_remove_confusing_call_subscription_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NetsapiensSubscriptionClient", 
            new_name="NetsapiensCallsSubscription"
        ),
    ]
