# Generated by Django 3.2.11 on 2022-01-27 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_voip_provider_active'),
        ('netsapiens_integration', '0007_rename_netsapiens_client_to_match_the_call_subscription_event_nomenclature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NetsapiensCallsSubscription",
            new_name="NetsapiensCallSubscriptions",
        ),
        migrations.RenameModel(
            old_name="NetsapiensCallsSubscriptionEventExtract",
            new_name="NetsapiensCallSubscriptionsEventExtract",
        ),
    ]
