# Generated by Django 3.2.11 on 2022-01-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_voip_provider_active'),
        ('netsapiens_integration', '0009_rename_foreign_keys_for_call_subscription_rename_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netsapienscallsubscriptions',
            name='voip_provider',
        ),
        migrations.AddField(
            model_name='netsapienscallsubscriptions',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='netsapienscallsubscriptions',
            name='practice_telecom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.practicetelecom'),
        ),
    ]
