# Generated by Django 3.2.12 on 2022-02-03 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0010_update_subscriptions_to_be_owned_by_telecom_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netsapienscallsubscriptionseventextract',
            name='netsapiens_call_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='netsapiens_integration.netsapienscallsubscriptions'),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='netsapiens_call_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='netsapiens_integration.netsapienscallsubscriptions'),
        ),
    ]
