# Generated by Django 3.2.12 on 2022-02-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0011_enforce_non_null_call_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsapienscallsubscriptions',
            name='source_id',
            field=models.CharField(blank=True, default='', help_text="Subscription ID for Netsapiens on the Voip Provider's side. The source of the data / events", max_length=32),
        ),
    ]
