# Generated by Django 3.2.12 on 2022-02-04 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0012_netsapiens_source_id_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsapienscdr2extract',
            name='netsapiens_call_subscription_event_extract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='netsapiens_integration.netsapienscallsubscriptionseventextract'),
        ),
    ]
