# Generated by Django 3.2.12 on 2022-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0013_add_optional_extract_id_to_cdr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='netsapienscdr2extract',
            name='peerlogic_call_partial_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=22),
        ),
    ]
