# Generated by Django 3.2.12 on 2022-02-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0015_prefix_cdrr_section_fields_so_that_we_capture_all_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netsapienscdr2extract',
            old_name='orig_callid',
            new_name='cdrr_orig_callid',
        ),
    ]
