# Generated by Django 3.2.13 on 2022-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netsapiens_integration', '0018_auto_20220330_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='by_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='by_group',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='by_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='by_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_from_host',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_from_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_from_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_from_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_group',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_logi_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_own_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_own_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_req_host',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_req_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_req_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_to_host',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_to_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='orig_to_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_group',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_logi_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_own_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_own_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscallsubscriptioneventextract',
            name='term_to_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='by_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_by_id',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_from_host',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_from_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_from_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_from_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_group',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_id',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_logi_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_req_host',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_req_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_req_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_to_host',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_to_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_orig_to_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_term_domain',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_term_group',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_term_id',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_term_logi_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_term_sub',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='cdrr_term_to_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='orig_from_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='orig_from_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='orig_req_uri',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='orig_req_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='netsapienscdr2extract',
            name='orig_to_user',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
